### ISSUE TITLE
Longer-term solution for handling DiscoveryRequestStreamObserver#onNext calls that occur after stream is closed

### ISSUE THREAD

**Issue by joeyb** [envoyproxy/java-control-plane#106]
Previous discussion: https://github.com/envoyproxy/java-control-plane/pull/105#discussion_r279771676.

`DiscoveryRequestStreamObserver#onNext` may receive messages after the `responseObserver` is closed (e.g. via `responseObserver#onError`). Calling `responseObserver#onError` twice causes an error, so we need some way to guard against calling it again.

Potential solution: check `isClosing` at the beginning of each `onNext` call. If true, log an error and return immediately.

**Comment by sschepens** [comment]
@joeyb we've hit this issue on the weekend, it left one of our CPs unable to push further updates to envoys. (since this errors are uncaught, our executors are getting shut down).
@jakubdyszkiewicz have u faced this issue? if so, how are you handling it?

Do we have solution for this? A couple of things come to my mind.
- We should catch all exceptions thrown when calling `responseObserver.onNext`
- We should check if `responseObserver` is already closed, probably via `isClosing` but this is not enough, since calls would have to be synchronized to prevent race conditions as `onNext` only needs to read the variable and not make any changes.
- I tend to think we should do as netty does and bind a `responseObserver` to a single `Thread`, this way, all the code inside it can be considered thread safe and ordered, this way we could have a boolean value, not need atomics and it would be safe. This si something that is initially possible because we are now able to provide and `ExecutorGroup` for streams, but we're only using it for stream responses, but the default remains `Executors.directExecutor()` which wouldn't actually guarantee ordering and thread safety here.

**Comment by slonka** [comment]
PR is merged so I'm closing this, please reopen if I'm missing something.
