### ISSUE TITLE
Publish initial maven artifact

### ISSUE THREAD

**Issue by snowp** [envoyproxy/java-control-plane#5]
Would it be possible to get a maven artifact uploaded so that we can consume it internally? Couldn't find anything on http://search.maven.org

We're eager to start playing around with this to see how this works in practice. If you feel this repo ready for an initial version yet I'll publish a jar internally, but I figured others might be interested in trying it out as well.

**Comment by joeyb** [comment]
Yup, getting releases configured in CircleCI is on my near-term TODO list. Hoping to get that sorted out in the next few days.

**Comment by joeyb** [comment]
Status update: I've kicked off the process for getting access to deploy to Maven Central (https://issues.sonatype.org/browse/OSSRH-37901).

**Comment by joeyb** [comment]
#7 adds an initial snapshot build. Remaining work:

- [ ] Configure gpg signing
- [ ] Configure CircleCI to perform the maven release process

**Comment by joeyb** [comment]
It took way more attempts than I had hoped, but this is fixed now. Signed release artifacts are being deployed to maven central: https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22io.envoyproxy.controlplane%22.

**Comment by cvgaviao** [comment]
@joeyb May I ask you to explain me why the circleci config.yml does not contain a release:perform, only a release:prepare ?

**Comment by joeyb** [comment]
@cvgaviao - It's been a while since I set the build up, so my memory on this is a little hazy. From what I remember, we're doing that because of the way that the maven release plugin ends up creating several separate commits. I kick off the release process by triggering a manual build with the `RELEASE` and `NEXT` parameters specified. That instructs the build to prepare a release, but it doesn't actually deploy anything in that build. We wait until the generated release commit gets built, then just issue [`mvn deploy` directly on it](https://github.com/envoyproxy/java-control-plane/blob/8274eed100adc0e369c5cd7f616542f2aff94f88/.circleci/config.yml#L49).

So the manually-triggered release builds are the only `master` builds that don't get deployed. Real releases are deployed on the generated `release: prepare release vx.x.x` commits, and snapshots are deployed for all others.
